sonar.projectKey=ecommerce-backend
sonar.projectName=E-commerce Backend
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.junit.reportsPath=target/surefire-reports
sonar.exclusions=**/config/**,**/dto/**,**/entities/**
sonar.coverage.exclusions=**/config/**,**/dto/**,**/entities/**,**/ECommerceApplication.java
sonar.qualitygate.wait=false
sonar.qualitygate.timeout=300